config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users
  resources :links do
    member do
      put 'like',     to: 'links#upvote'
      put 'dislike',  to: 'links#downvote'
    end
    resources :comments
  end
  root 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Link.find(params[:link_id]).comments.all
  end

  def new
    @comment = Comment.new
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    set_link
    @link.upvote_from current_user
    redirect_to :back
  end

  def downvote
    set_link
    @link.downvote_from current_user
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_name(user)
    if user.name.blank?
      user.email
    else
      user.name
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    User:
    <%= current_user.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Reddit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    /! Fixed navbar
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"
            strong style="color:#222;" LUVV
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li= link_to "Home", root_path
            - if user_signed_in?
              li= link_to "New Link", new_link_path
              li= link_to "Account (#{current_user.email})", edit_user_registration_path
              li= link_to "Sign Out", destroy_user_session_path, :method => :delete
            - else
              li= link_to "Sign In", new_user_session_path
              li= link_to "Register", new_user_registration_path
        /! /.nav-collapse


    .container
      .wrapper
        p.notice= notice
        p.alert= alert

        = yield

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">Submit your link below</div>

    <div class="panel-body">
      <form>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :url %><br>
          <%= f.text_field :url, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
      </form>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.slim
- @links.each do |link|
  h3= link_to link.title, link
  p
    = "Submitted " + time_ago_in_words(link.created_at) + " ago by "
    = display_name(User.find(link.user_id))

  .btn-group.main_actions
    = link_to "Visit Link", "#{link.url}" ,class: "btn btn-xs btn-default"
    = link_to "<span class='glyphicon glyphicon-menu-up'></span> Upvote ".html_safe + "#{link.get_upvotes.size}", like_link_path(link), method: :put, class: "btn btn-xs btn-default"
    = link_to "<span class='glyphicon glyphicon-menu-down'></span> Downvote ".html_safe + "#{link.get_downvotes.size}", dislike_link_path(link), method: :put, class: "btn btn-xs btn-default"

  | &nbsp;
  - if link.user == current_user
    .btn-group.pull-right
      => link_to 'Edit', edit_link_path(link), class: "btn btn-xs btn-default"
      = link_to 'Destroy', link, method: :delete, data: { confirm: ('Are you sure?') }, class: "btn btn-xs btn-default"

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.slim
h3= link_to @link.title, @link
p
  = " - Submitted " + time_ago_in_words(@link.created_at) + " ago by "
  = User.find(@link.user_id).email

.btn-group.main_actions
  = link_to "Visit Link", "#{@link.url}" ,class: "btn btn-xs btn-default"
  = link_to "<span class='glyphicon glyphicon-menu-up'></span> Upvote ".html_safe + "#{@link.get_upvotes.size}", like_link_path(@link), method: :put, class: "btn btn-xs btn-default"
  = link_to "<span class='glyphicon glyphicon-menu-down'></span> Downvote ".html_safe + "#{@link.get_downvotes.size}", dislike_link_path(@link), method: :put, class: "btn btn-xs btn-default"

| &nbsp;
- if @link.user == current_user
  .btn-group.pull-right
    => link_to 'Edit', edit_link_path(@link), class: "btn btn-xs btn-default"
    = link_to 'Destroy', @link, method: :delete, data: { confirm: ('Are you sure?') }, class: "btn btn-xs btn-default"


br
br
br
h3= "Comments (#{@link.comments.count})"

= simple_form_for [@link, Comment.new] do |f|
  = f.input :body, as: :text, label: false
  = f.button :submit, class: 'btn btn-primary'

- @link.comments.reverse.each do |comment|
  hr
  p
    strong= "Posted " + time_ago_in_words(comment.created_at) + " ago by "
    strong= comment.user.email
  p= comment.body